[platformio]
default_envs = nicemcu-32s-dev

[env:nicemcu-32s-dev]
platform = espressif32 @ 7.0.1
board = esp32dev
framework = arduino

monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
monitor_filters = esp32_exception_decoder

build_flags =
    -Ofast
    -Wall
    -Iinclude
    -D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO
    -D LV_CONF_INCLUDE_SIMPLE

lib_deps =
    lvgl/lvgl @ 9.5.0
